name: Terraform AI Review

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-ai-review:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Tools
        run: |
          terraform version
          python3 --version

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --user openai requests distro checkov

      - name: Terraform Init
        run: |
          terraform init \
            -input=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Convert Plan To Text
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Run AI Review
        run: |
          python3 ai/ai_review.py > ai-report.txt

      - name: Show AI Report
        run: |
          cat ai-report.txt

      - name: Send Slack Report
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python3 ai/slack_send.py
